resources:
  - name: autoTrigger
    type: CronTrigger
    configuration:
      interval: '0 12 * * *'
  - name: helloWorldContainerImage
    type: Image
    configuration:
      registry: JFrogCR
      sourceRepository: default-docker-virtual
      imageName: hello-world
      imageTag: latest

pipelines:
  - name: CronPipeline
    steps:
      - name: ImageList
        type: Bash
        configuration:
          integrations:
            - name: JFrogCR
          inputResources:
            - name: autoTrigger
        execution:
          onExecute:
            - docker image ls
