resources:
  - name: autoTrigger
    type: CronTrigger
    configuration:
<<<<<<< HEAD
      interval: '0 12 * * *'
  - name: helloWorldContainerImage
    type: Image
    configuration:
      registry: JFrogCR
      sourceRepository: default-docker-virtual
      imageName: hello-world
      imageTag: latest
=======
      interval: '30 12 * * *'
>>>>>>> 0f982e262c67a3468914e9d8ad1b5d92038cb1e5

pipelines:
  - name: CronPipeline
    steps:
      - name: ImageList
        type: Bash
        configuration:
          integrations:
            - name: JFrogCR
          inputResources:
            - name: autoTrigger
        execution:
          onExecute:
            - docker image ls
