resources:
  - name: autoTrigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'

pipelines:
  - name: CronPipeline
    steps:
      - name: ImageList
        type: Bash
        configuration:
          inputResources:
            - name: autoTrigger
        execution:
          onExecute:
            - env
