resources:
  - name: autoTrigger
    type: CronTrigger
    configuration:
      interval: '30 12 * * *'
  - name: helloWorldContainerImage
    type: Image
    configuration:
      registry: JFrogCR
      sourceRepository: default-docker-virtual
      imageName: nvarun.jfrog.io/default-docker-virtual/hello-world
      imageTag: latest

pipelines:
  - name: CronPipeline
    steps:
      - name: HelloWorld
        type: Bash
        configuration:
          inputResources:
            - name: autoTrigger
            - name: helloWorldContainerImage
        execution:
          onExecute:
            - uname -a
            - date
            - docker run ${res_helloWorldContainerImage_imageName}
