resources:
  - name: autoTrigger
    type: CronTrigger
    configuration:
      interval: '30 12 * * *'
  - name: helloWorldContainerImage
    type: Image
    configuration:
      registry: JFrogCR
      sourceRepository: default-docker-virtual
      imageName: nvarun.jfrog.io/default-docker-virtual/hello-world
      imageTag: latest

pipelines:
  - name: CronPipeline
    steps:
      - name: C0001
        type: Bash
        configuration:
          inputResources:
            - name: autoTrigger
        execution:
          onExecute:
            - docker ps -a
      - name: C0002
        type: Bash
        configuration:
          inputResources:
            - name: helloWorldContainerImage
          inputSteps:
            - name: C0001
        execution:
          onExecute:
            - env | grep ^res_
            - docker run ${res_helloWorldContainerImage_imageName}
