resources:
  - name: autoTrigger
    type: CronTrigger
    configuration:
      interval: '30 11 * * *'
  - name: nginxContainerImage
    type: Image
    configuration:
      registry: JFrogCR
      sourceRepository: default-docker-virtual
      imageName: hello-world
      imageTag: latest
      
pipelines:
  - name: CronPipeline
    steps:
      - name: PullandRunImage
        type: Bash
        configuration:
          integrations: [
            'JFrogCR'
          ]
          inputResources:
            - name: autoTrigger
        execution:
          onExecute:
            - docker image ls
    
